### ISSUE TITLE
Add a max height and scrolling to Modal

### ISSUE THREAD

**Issue by henningmu** [Doist/reactist#127]
Like the top margin of 60px it should have the same to the bottom and ensure the content (aka the Modal.Body) scrolls correctly.

**Comment by henningmu** [comment]
Exactly. The problem is when the Modal.Body grows larger (e.g. because it contains a table) or when the height is too small the blackish overlay scrolls. I'd prefer it when the Modal.Body begins scrolling as soon as the full modal exceeds the height of 100%-120px. 

![screenshot 2018-11-06 at 07 44 28](https://user-images.githubusercontent.com/6048870/48047366-1e093a80-e198-11e8-9ecf-00651c94cf37.png)

**Comment by kylemh** [comment]
I've been playing around with this quite a bit, and the behavior you seek isn't achieved with constraining just the max-height of `Modal.Body`. I feel like there are a few ways to tackle the issue, but not without asking a few questions:

a) How do you feel about constraining the min & max-height of `Modal.Header` and `Modal.Footer` and giving them auto vertical scroll as well? There's nothing to prevent a developer from filling either with so much content that this becomes a multi-faceted problem.

b) How do you feel about ditching the [overlay-inner](https://github.com/Doist/reactist/blob/dev/src/components/Modal.jsx#L59) div and instead centering and constraining the modal via `margin: auto;` + `max-height: calc(100vh - 120px);`? I've taken inspiration from Christian Longe's comment in [this CSS tricks article](https://css-tricks.com/considerations-styling-modal/) in the past.

In terms of checking for edge cases, I'll be rendering the modal in a viewport height of 320px and width of 320px at worst (iPhone SE, horizontal and vertical).

**Comment by kylemh** [comment]
Yeah, we can keep closeOnOverlayClick working. We'll just preventDefault on the actual modal, so only clicks on the absolutely positioned full view overlay (where the modal does not exist) will close the overlay.

**Comment by gnapse** [comment]
This issue no longer applies as our new modal (being developed in #547) already covers these features being requested here. The new modal will be released later this week to beta.
