### ISSUE TITLE
Remove moment as (peer) dependency 

### ISSUE THREAD

**Issue by henningmu** [Doist/reactist#128]
I think there are slimmer alternatives with similar APIs. Might be worth looking at (a) native browser implementations or (b) date-fns

**Comment by gnarmedia** [comment]
I'm messing with this, it seems like it shouldn't be too bad to use the native api

**Comment by henningmu** [comment]
Awesome 🙌 Please note the `config` we pass into the `Time` component. I'd like to keep that and also please include a link to the browser support (caniuse.com) for the APIs you decide on 👍

**Comment by gnarmedia** [comment]
Sounds good!

**Comment by gnarmedia** [comment]
So I made a commit to see what you think of my approach: https://github.com/gnarmedia/reactist/commit/6b4849f2075fd9c83ad478392418fce684c21f2a

The Date APIs used are:

getFullYear - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getFullYear
toLocaleString - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
now - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now
getDay - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay

other dependencies:
date-fns (modular date functions) - https://github.com/date-fns/date-fns
mockdate (needed to mock the date in TimeUtils, could be extracted if needed) - https://github.com/boblauer/MockDate

I'll keep going with this, but if you want anything changed, just let me know!

Thanks!

**Comment by gnarmedia** [comment]
I'm noticing my changes won't build, it fails looking for date-fns, seems I did something wrong. I'll look into it tomorrow.

**Comment by henningmu** [comment]
Looks already very good. I have a couple of remarks:
1. Internally we need to support more languages than date-fns currently does. One solution could be to add a `format` function to config paramter which defaults to the date-fns. So other users can use date-fns and we'd supply our own. Also we should throw an Error if neither a function is supplied nor date-fns is found.
2. I think you can move the helper functions (`unix`, `seconds`, ...) into TimeUtils and export them. No harm in that
3. From [this discussion](https://github.com/facebook/jest/issues/2234) it seems to be possible to mock `new Date()` with jest. Maybe you could try that instead of `mockdate`?

**Comment by gnarmedia** [comment]
Ok, I've removed mockdate, fixed the mocked date, and revised the way I was setting the day of the week to Monday for the test on line 59.

I haven't had a chance to look into formatting for date-fns/moment yet.

**Comment by gnarmedia** [comment]
As for formatting, what languages which are missing do we need to support? Would support be that hard to add? Is it a bunch? Maybe it's best for the future as even if I did try to contribute the other languages to date-fns (which would help them) I'd still need to work to be sure the translations were correct.

**Comment by gnarmedia** [comment]
Oh, awesome, I'm glad all are supported! Ok, I'll update date-fns to version 2 tonight!

**Comment by henningmu** [comment]
Closed by #158
