### ISSUE TITLE
Prettier pre-commit hook

### ISSUE THREAD

**Issue by kylemh** [Doist/reactist#134]
### ⚙️ Improvement
Leverage [Husky](https://github.com/typicode/husky) and [Precise-Commits](https://github.com/nrwl/precise-commits) with a [pre-commit hook](https://github.com/nrwl/precise-commits#2-precommit-hook) in order to format per commit, ensuring that linting and formatting is constantly maintained while avoiding any git pollution.

### ❓Reasoning
I have Prettier integrated into my editor, and your codebase uses Prettier; however, files required formatting before making any changes. This indicates one or both of the following are true:
1) The entire codebase needs formatting against using the command:

```prettier --write "**/*.(js|less)"```

2) Incorrectly formatted code is entering the code base.

---

This improvement prevents number 2 from ever happening again, and number 1 can be solved permanently by running the aforementioned command _after_ this issue is resolved. 😎 

(I'd love to take this if it's something y'all desire)

**Comment by henningmu** [comment]
Oh wow I wasn't aware of this. Thanks for bringing it to our attention 👍 
Would love if for you take on this issue one question though: Why do we need precise-commits? Couldn't we add a pre-commit hook that formats the whole codebase? As soon as we fixed number 1 it should only be the files you touched anyway, right?

**Comment by gnarmedia** [comment]
You can add prettier + husky + pre-commit (node package to keep git commit hook code in node)

**Comment by gnarmedia** [comment]
I do this sometimes, we do it at work and it's great

**Comment by kylemh** [comment]
I've opened the PR #135 

To explain further:
The pre-commit hook only formats _changed_ code. When adding the pre-commit hook, it wont format the whole code base. We'll basically require one manual blast with a `prettier "**/*" --write"` and then the pre-commit hook will keep everything pretty ✨

One exception: When Prettier updates to a version that changes formatting, you'll want to format your entire repository again. This doesn't happen too often, but often enough to be aware of.
