### ISSUE TITLE
Implement Modal using Portals

### ISSUE THREAD

**Issue by jvalente** [Doist/reactist#149]
The existent Reactist.Modal component is [coupled with the existence of a DOM element #modal_box](https://github.com/Doist/reactist/blob/dev/src/components/Modal.jsx#L208).

It seems like [Portals](https://reactjs.org/docs/portals.html) can be used to implement this component in a more elegant manner.

**Comment by gnarmedia** [comment]
I can try working on this, portals are pretty straight forward.

**Comment by gnapse** [comment]
Already covered by our newest modal being implemented in #547, which will land on beta by the end of this week.
