### ISSUE TITLE
Tooltip Issue and Proposal

### ISSUE THREAD

**Issue by stkao05** [Doist/reactist#164]
This issue outlines some issues with the current Tooltip component implementation, and also suggest some proposed change.

## Issues

__1. The Tooltip HTML ins't friendly for layout.__

Suppose you have a button which you want to add a tooltip.

```js
<div className="button_container">
    <Tooltip text={_("Edit")}>
        <EditButton />
    </Tooltip>
</div>
```

The Tooltip component will wrap the button component with its HTML.

```js
<div className="button_container">
    <span class="reactist popover__wrapper reactist tooltip__wrapper">
        <button />
        <span class="reactist popover" style="top: 276.25px; left: 1033.81px;">
        <span class="reactist popover__content reactist tooltip__text">Edit</span>
        </span>
    </span>
</div>
```

`button` is no longer a direct child of `button_container`, but rather the `tooltip__wrapper`. This could make CSS layout trickily in some scenario. Ideally, the tooltip should not insert extra HTML to the tooltip target and also its container.

__3. The HTML mockup structure is not friendly for browser rendering performance__

Each tooltip is placed beside the target element. 

The more optimize HTML structural will be to place tooltip as an immediate child of `<body>`
```js
<body>
    ....
<div className="tooltip">Edit</div>
</body>
```

__2. Tooltip is always rendered even when not show__

We want to support the lazy rendering of a tooltip - only render tooltip when it is showing, because some tooltip could be expensive to render.

For instance, Todoist's due date tooltip

<img width="658" alt="Screen Shot 2019-05-28 at 5 03 45 PM" src="https://user-images.githubusercontent.com/1556390/58465742-e6310700-816a-11e9-8abf-fad682d89dd3.png">
 

#### Proposal

- The Tooltip does not introduce any mockup to the target component and it will be rendered as an immediate child of `<body>`

- The Tooltip should be lazy rendered: it's only rendered when the target component is on-hovered. Should be great if Tooltip could accept a function() if lazy rendering is needed

```js
<Tooltip content={renderExpensiveComponent}>
</Tooltip>
```

Reference: [Material UI Tooltip](https://material-ui.com/components/tooltips)

**Comment by henningmu** [comment]
I fully agree with the outlined problems and proposed solution. 
One thing: this should be fixed on the level of the underlying `Popover` component ideally the Tooltip component wouldn't even need to change 👍

**Comment by stkao05** [comment]
@henningmu I am considering to re-implement the tooltip with the help of a positioning library https://github.com/FezVrasta/popper.js  It is used quite widely by library such as AtlasKit,  Bootstrap and Material UI.  What do you think?

**Comment by henningmu** [comment]
@stkao05 I initially tried to solve this without introducing a 3rd party library, however, if you think its needed please go ahead 👍

**Comment by gnapse** [comment]
May I suggest using https://ui.reach.tech/tooltip instead?

**Comment by stkao05** [comment]
Had a brief look at reach's tooltip, but I don't think it will fit our usage as they seem to only support text-only tooltip. 

They implement their tooltip via CSS pseudo-element.

```
.react-live-preview:before {
    content: "Preview";
}
```

**Comment by gnapse** [comment]
Fair enough. In that case I hope we at least make our Tooltips accessible. It is not a trivial task, but tooltips are supposed to be shown automatically not just on mouse over, but when the focusable element around which its placed gets the focus. And get somehow to have assistive technologies read the tooltip content.

**Comment by gnapse** [comment]
> Had a brief look at reach's tooltip, but I don't think it will fit our usage as they seem to only support text-only tooltip.

Not sure if that was never the case, or if they fixed it, but [@reach/tooltip](https://reacttraining.com/reach-ui/tooltip/) seems to no longer be limited to text-only tooltips.

I seriously recommend looking into the viability of using those instead of rolling out our own. It's polished in many ways.

**Comment by stkao05** [comment]
Geat to know that reach-ui tooltip has improved its tooltip implementation. Taking a deeper look, one minor thing I am not sure about is its [fixed timeout value](https://github.com/reach/reach-ui/blob/master/packages/tooltip/src/index.tsx#L67) which control when the tooltip disappeared. It would be great if we can customize it to the experience we desired.

---

Generally speaking, I am preferring keeping in-house implementation of these UI components. The reason isn't that reactist code is better, as  I am sure there are many other libraries out that outperform it.  But I feel the very first the reason we start reactist is so that we could have full control of its code, style, and dependencies.

**Comment by gnapse** [comment]
I'd rather have a better supported and battle tested component, than an in-house one where we can control its code. We can always raise issues in those component's open source repositories, and even contribute to their code with improvements and bug fixes.

And this is what I'd do with that issue you mention about ReachUI's tooltip. It may be that we can fix that, making it customizable. Or I can even imagine there are sensible reasons behind those defaults (e.g. I can imagine that precisely for accessibility reasons tooltips should be as quick as ours, though this is speculation, not saying that that is the case right now). Or it could even be that our timeout values are not something we hold too dear, and that we can perfectly live with their defaults. Are they?

**Comment by stkao05** [comment]
Alright, I think we can give it a try, given that it is relatively lightweight.

**Comment by gnapse** [comment]
That's great. Thanks!

BTW, I now think the timeout is not accidental: immediately showing the tooltip on every hover is not good UX: https://share.getcloudapp.com/L1ugpNrv

And as for customizing it, I'd assume they want to keep the API simple. Is not big deal a few or less milliseconds. Their default seems like a reasonable standard for all cases.
