### ISSUE TITLE
CSS namespace issue

### ISSUE THREAD

**Issue by stkao05** [Doist/reactist#174]
Current the component css use an extra "reactist" class to serve as namespacing to prevent reactist css from "leaking out"  to library user styling.

```
// html
<span class="reactist popover>

//css 
.reactist.popover {

}
```

So if the user of the library happens to create a new popover element in a different context, the reactist css won't be applied to the element.

However, the user still cannot implement a separate element with the same classname `popover`, as any CSS styling to this component will unintentionally affect reactist popover component

```
// my new popover component 
.popover {

}
```

------

If we want to allow more portability of this library, I think it might be better to use apply namespace as `reactist_popover` or `r_popover`.

**Comment by gnapse** [comment]
This was closed/fixed in #184
