### ISSUE TITLE
Broken Knobs in storybook.

### ISSUE THREAD

**Issue by Nazeh** [Doist/reactist#185]
### 🐛 Bug (Docs: storybook)

Version 2.0.2

### Issues

- **Minor**: illegal mix of CSF default export and storiesOf calls in a single file.
related: https://github.com/storybookjs/storybook/issues/9196
Solved at: https://github.com/Nazeh/reactist/commit/c2e012ad8adf5aca8de1fc474ee46c84b13f4812 by using `export const Story` instead of `export default Story`

- **Inactive Knobs**: Some of the components' Stories contain broken knobs that don't change the component's props, namely:
  - [Checkbox](https://rawcdn.githack.com/Nazeh/reactist/0538ed536fb2895757c2fce8affce34ee88120d4/docs/index.html?path=/story/checkbox--component-playground)
  - [Input](https://rawcdn.githack.com/Nazeh/reactist/0538ed536fb2895757c2fce8affce34ee88120d4/docs/index.html?path=/story/input--component-playground)
  - [Select](https://rawcdn.githack.com/Nazeh/reactist/0538ed536fb2895757c2fce8affce34ee88120d4/docs/index.html?path=/story/select--component-playground) 
  
  - [Tabs](https://rawcdn.githack.com/Nazeh/reactist/0538ed536fb2895757c2fce8affce34ee88120d4/docs/index.html?path=/story/tabs--component-playground)

This can be a problem as the storybook is a final check for corner cases that are not covered in tests.
I already missed a bug because of that and solved it later here https://github.com/Doist/reactist/pull/184/commits/e66098b5a43d117f4e22d8c77cdd4f5f8da2cbad

I am not sure what is causing this problem, as I have little experience with Storybook. but if I found out I will be opening a new PR for it.

**Comment by markpalfreeman** [comment]
Hi, I'm a Doist fan and was browsing small issues to contribute to the project.

I pulled this down and can't repro; those components' knobs work just fine—is it still a problem?

**Comment by gnapse** [comment]
Indeed, our storybook was updated recently and we have not been paying attention to keep it up with stale issues like this. I'm closing this now.
