### ISSUE TITLE
Potential bug in TimeUtils

### ISSUE THREAD

**Issue by proxi** [Doist/reactist#189]
In:

https://github.com/Doist/reactist/blob/2b22b066a7038acf306122f63da2b655bba1243d/src/components/utils/TimeUtils.js#L24

it looks like unit parameter `'minutes' | 'hours' | 'days'` is invalid. [TypeScript reports it](https://github.com/Doist/reactist/pull/188) and I checked in dayjs source code that there's no such constant.

I was probably broken by https://github.com/Doist/reactist/pull/158

**Comment by henningmu** [comment]
Yup, should use `minute`, `hour`, `day` according to docs: https://day.js.org/docs/en/display/difference

**Comment by henningmu** [comment]
We could probably also drastically simplify this component based on our usage in Twist and bump a major version
