### ISSUE TITLE
PropTypes for Button component do not include 'close'

### ISSUE THREAD

**Issue by proxi** [Doist/reactist#198]
### 🐛 Bug

Refer to this issue in Twist for details: https://github.com/Doist/twist-web/issues/1865

**Comment by rimildeyjsr** [comment]
@proxi - Hey! Can I work on this?

**Comment by gnapse** [comment]
We will be removing the `close` props from buttons really soon, so I am not sure it is worth it.

That being said @rimildeyjsr I wouldn't reject a contribution offer so I'd recommend you to work on removing the `close` prop. It could be something we include in an upcoming major release that will include other breaking changes.

**Comment by rimildeyjsr** [comment]
@gnapse - Thank you 😃 Will send a PR when it's ready! Also, it's my first time looking into the codebase, so if I have any questions I will ask them as well!
