### ISSUE TITLE
Do we need built assets in git

### ISSUE THREAD

**Issue by gnapse** [Doist/reactist#252]
### ⚙️ Improvement

I wonder if we need to have checked in git all the files generated from a build. That hasn't been my experience working in other libraries. Though I have to admit I am not knowledgeable at all when it comes to all the build/config parts of the job so I'm not even sure what the implications are in terms of publishing, etc.

**Comment by henningmu** [comment]
I think it's not needed for publishing as `npm publish` runs the `prepare` scripts which generates the assets. I'm not sure about linking reactist it into Twist / Todoist, but if that works let's go for it 👍

Also @vishnugopal in case I overlooked something

**Comment by clempat** [comment]
Sorry to jump on the discussion. I don't want to be invasive. 

I think the problem you could face by adding any generated files into Github is conflicts hard to resolve. It should not be a problem when it comes to the isolated components files but could be more difficult with file like `dist/reactist.cjs.production.min.js` or `dist/reactist.cjs.development.js`.

If you want to have access to assets for every version you could setup some CI to add releases in Github.

At Quandoo, We use https://github.com/semantic-release/semantic-release and it is a really good tool.It comes with some requirements though such as following certain commits format.

But I am maybe off... Sorry

**Comment by gnapse** [comment]
@clempat the discussion I brought up here is precisely towards ceasing to do this, which we already do. Sorry it was not clear from the original issue description, which I can see it is ambiguous and could be interpreted as proposing to do this. It is really proposing to stop doing it.

**Comment by clempat** [comment]
Oh thanks for the precision @gnapse. I missed it because I was looking to the dist folder which is not there. But now I think I see what you mean.

So my new guess is you speak about the storybook static files (docs folder) which was probably done this way to be served by GitHub pages ?

https://github.blog/2016-08-22-publish-your-project-documentation-with-github-pages/

**Comment by vishnugopal** [comment]
Linking Reactist into Twist or Todoist also should run prepare so +1 for this! 👏
