### ISSUE TITLE
Reduce width of the `Switch` component to 32px

### ISSUE THREAD

**Issue by craigcarlyle** [Doist/reactist#375]
### Motivation

Design has requested that the `Switch` component in both Todoist and Twist be `32px` wide. Let's change it in Reactist instead of manually setting it in both.

**Comment by gnapse** [comment]
Hmmm, there's no Switch component in Reactist. I think it's one of those components that appeared first in one of the apps, then copied over to the other app instead of being extracted to Reactist. Maybe this issue can be about doing that.
