### ISSUE TITLE
Modal size with 'large' as true is smaller than with 'medium' as true

### ISSUE THREAD

**Issue by nats12** [Doist/reactist#521]
### Current behavior

Currently, the modal's size when setting `large` to `true` is slightly smaller than when setting `medium` to `true`.

Medium:

![image](https://user-images.githubusercontent.com/15801768/118607980-7eda4a80-b7b9-11eb-8017-6d5cdd038dc4.png)

Large: 
![image](https://user-images.githubusercontent.com/15801768/118607998-839efe80-b7b9-11eb-9ef6-23ccda739ec2.png)

### Steps to reproduce the bug

- Visit http://doist.github.io/reactist/?path=/story/components-modal--modal-playground-story
- Set `large` to `true`, then set `medium` to `true`
- Set `large` to `false` - notice that the size increases with just `medium` enabled 

Inspecting the elements as above also shows the change in widths.

### Expected behavior

The large variant of modal should be wider than the medium variant.

### Possible solutions

I think the styles here may be conflicting with one another:

<img width="836" alt="Screenshot 2021-05-17 at 19 43 09" src="https://user-images.githubusercontent.com/15801768/118608304-daa4d380-b7b9-11eb-9747-7f4a241cad49.png">

as the calculation is applied on both `&.large` and to the container in general.

### Environment

-   Browser: Chrome
- 	OS: macOS

**Comment by gnapse** [comment]
This is no longer a problem under our new modal (see #547) which will land on beta later this week.
