### ISSUE TITLE
Avatar: Allow responsive sizes

### ISSUE THREAD

**Issue by scottlovegrove** [Doist/reactist#605]
### Motivation

One of the great things about the new components is the responsive nature, being able to set a value for mobile/desktop/tablet. I realise that Avatar is one of the original components, but I think the `Avatar` component could definitely do with it.

### Example

This is currently what I have where `isMobile` is something from [`react-device-detect`](https://www.npmjs.com/package/react-device-detect), but it means it's not truly responsive.
```
<Avatar
    size={isMobile ? 'l' : 'xl'}
    avatarUrl={authenticatedUser.avatarUrl}
    user={{
        name: authenticatedUser.name,
        email: authenticatedUser.emailAddress,
    }}
/>
```
What I'd like to be able to do is
```
<Avatar
    size={{
        mobile: 'l',
        desktop: 'xl',
    }}
    avatarUrl={authenticatedUser.avatarUrl}
    user={{
        name: authenticatedUser.name,
        email: authenticatedUser.emailAddress,
    }}
/>
```

**Comment by gnapse** [comment]
Indeed. The avatar component predates the newer way we do components. And this is certainly something that makes sense.

Would you be open to make the contribution yourself? Ideally it would involve not merely adding this feature, but refactoring the avatar component to be implemented internally in ways similar to how the new components are, including moving its styles to CSS modules using CSS variables, and dog-fooding internally the use of the newer component (e.g. preferring `Box` to reuse all its styling capabilities, etc.)

**Comment by scottlovegrove** [comment]
> Would you be open to make the contribution yourself?

Sure 👍🏻
