### ISSUE TITLE
Compatibility with React 17.x

### ISSUE THREAD

**Issue by proxi** [Doist/reactist#645]
### Current behavior

`package.json` lists `react` with `|| ^17.0.0`, but at the same time requires `"reakit": "1.3.0"`, which requires `react ^16.8.0`, [ref.](https://github.com/ariakit/ariakit/blob/57b1238e714bb4dda3984d62268313c180fcc6a8/packages/reakit/package.json#L49), making it impossible to resolve dependencies.

### Steps to reproduce the bug

If possible, provide a repo or sandbox with the bug and describe the steps to reproduce it.

### Expected behavior

Explain how it should behave.

### Possible solutions

If possible, describe how this bug could be fixed.

### Environment

-   `@doist/reactist` version: 11.0.0
-   `react` version: 17.0.2
-   Browser:

**Comment by frankieyan** [comment]
Closed via https://github.com/Doist/reactist/pull/662
