### ISSUE TITLE
Storybook complains about addon channel, no components displayed

### ISSUE THREAD

**Issue by RadValentin** [Doist/reactist#66]
I'm running into an issue where storybook won't display any of the components in this repo. Instead I get this cryptic message in the console:
```
Uncaught Error: Accessing nonexistent addons channel, see https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel
```

As the docs [suggest](https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel), the fix is to remove `node_modules` and `yarn.lock` and rebuild the lockfile. Clearly there's a problem with the way dependencies get installed. Is this happening to anyone else? 

My env:
```
yarn@1,3,2
node@8.6.0
Windows 10
```

**Comment by henningmu** [comment]
Hey @RadValentin ,

sorry for coming back to you so late. I just tried to reproduce this with a clean checkout and `npm install` as well as `yarn install` and didn't run in any problems.

Did the removal of node_modules and lock file work you?

```
npm@5.6.0
yarn@1.3.2
node@8.6.0
macOS 10.13.2 Beta
```

**Comment by RadValentin** [comment]
@henningmu Yes, removing `node_modules` and rebuilding the lockfile worked. I ran some more tests in the meantime, tested both on `master` and `dev` branches. Here are my findings:

1. Tested on `macOS 10.11.6` and got same problem as in Windows 10
1. `yarn install` on clean repo always makes changes to `yarn.lock` (~16 changes)
1. Deleting old lockfile and rebuilding it fixes the problem for future installs

 I'd really like to get to the bottom of this. I think the lockfile got corrupted somehow and it needs to be rebuilt and committed to the repo. Can you check two more things for me?

1. Did `yarn install` make change to `yarn.lock` when you tested?
1. What happens when you run the steps below? The `yarn cache clean` part is what I think we did differently.

```sh
git checkout dev
rm -rf node_modules
yarn cache clean
yarn install
yarn storybook
```
Thanks!

**Comment by henningmu** [comment]
Still works for me but I think I found the problem. We have a `package-lock.json` (which is kept up to date as I mainly use npm) and a `yarn.lock` which is pretty stale. I think removing the `yarn.lock` from the repo will clean this up for you and potentially others 😊

Thanks for taking the time and reporting this 🎉

**Comment by RadValentin** [comment]
Sounds good. I can confirm that on `npm install` it storybook works as expected. It sucks that we couldn't figure out what was wrong with yarn but it's probably for the best since it wasn't being used anyway.

@henningmu I'll make the PR if it's ok with you, let me know.

**Comment by henningmu** [comment]
Sure would love that. Thank you 🙌
