### ISSUE TITLE
Remove gaps between tabs on Web

### ISSUE THREAD

**Issue by henningmu** [Doist/reactist#762]
## Description

There is an unnecessary gap between tabs in the Tab component. It seems like a `4px reactist xsmall gap`. We don't need that.

## Expected behaviour

Remove the gap between tabs for a more comfortable usage between them. For example in Twist's Inbox.

## Screenshots

**Before**
![image](https://user-images.githubusercontent.com/7838670/226940440-c1b9912a-1930-4513-b618-965d4e1bd6fd.png)

**After**
![image](https://user-images.githubusercontent.com/7838670/226940541-1b8bf146-82d3-4a1b-a7ab-d445a87a2443.png)

**Comment by agarwal-aryan** [comment]
Can you please elaborate the problem and also provide the path to the files in which we can work upon?

**Comment by henningmu** [comment]
What more information apart from the screenshots and the initial issue description do you need to work on this? :)

The file is here: https://github.com/Doist/reactist/blob/main/src/tabs/tabs.tsx – my gut feeling tells me, it's the `space = 'xsmall',` in the `TabsList` that we need to remove, but would need confirmation 👍

**Comment by MahirMahdi** [comment]
Is this issue still open?

**Comment by gnapse** [comment]
It is still open @MahirMahdi.

**Comment by MahirMahdi** [comment]
@gnapse when I run storybook, it works fine but the styles are not applied.
![Screenshot 2023-05-31 075032](https://github.com/Doist/reactist/assets/66949598/5575952e-137a-4e04-9842-07440db9dcc3)

**Comment by MahirMahdi** [comment]
@gnapse When I first ran it it showed this error : "✖ Failed to compile
(styles plugin) Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer".

After I initialized it, it started showing this: "(styles plugin) TypeError: fetch failed". Can you please help me with it?

**Comment by MahirMahdi** [comment]
@gnapse Can I work on it? @henningmu is right, removing `space = 'xsmall'` removes unnecessary gap.

**Comment by MahirMahdi** [comment]
@gnapse Can I work on it? @henningmu is right, removing `space = 'xsmall'` removes unnecessary gap.

By default( with `space = 'xsmall'` ):

![Screenshot 2023-05-31 083300](https://github.com/Doist/reactist/assets/66949598/69769bc6-cfc5-411e-96c2-2a3632367b13)

After removing  `space = 'xsmall'`: 

![Screenshot 2023-05-31 083519](https://github.com/Doist/reactist/assets/66949598/64053fa5-66fd-46c0-8e13-7e5b1fe84b66)

**Comment by henningmu** [comment]
@MahirMahdi yes, please feel free to submit a PR 👍

**Comment by MahirMahdi** [comment]
@henningmu Thanks. On it.
