### ISSUE TITLE
TextArea with autoExpand={true} expands horizontally when typing long text without spaces

### ISSUE THREAD

**Issue by gnapse** [Doist/reactist#776]
### Current behavior

In a `TextArea` with `autoExpand` enabled, when typing a long text without a space in it, the text area can become wider than intended.

Admittedly, it is not common for anyone to type long texts without any space in it. While at the same time, it is not exactly a disruptive behavior that the text area expand. Usability is not really affected. So this is a nice-to-have.

### Steps to reproduce the bug

Visit the [TextArea autoExpand story in storybook](https://doist.github.io/reactist/?path=/docs/design-system-textarea--auto-expand-story) and start typing in the textarea at the top, the one that has a label saying that it has auto-expand enabled.

### Expected behavior

Ideally we could make the text wrap, even if not at a word boundary, and have the text area width to be kept no matter what.

### Possible solutions

I quickly tried enforcing the `textarea`'s width by using combinations of `width: 100%`, `max-width: 100%`, `overflow`, etc. No luck so far.

### Reference

Reported by @engfragui [here](https://github.com/Doist/todoist-web/pull/6715#discussion_r1203967084).

**Comment by MahirMahdi** [comment]
But here the text area is working just fine. Please let me know if this is what you're talking.
![Screenshot 2023-06-04 113106](https://github.com/Doist/reactist/assets/66949598/ea13fca7-f95b-4545-8f5e-687ea5e5eb71)

**Comment by gnapse** [comment]
Please, go to [this storybook story](https://doist.github.io/reactist/?path=/docs/design-system-textarea--auto-expand-story) and start typing in a text area at the top (the one that says it has auto-expand enabled). You should be able to reproduce:

<img width="655" alt="CleanShot 2023-06-05 at 08 20 31@2x" src="https://github.com/Doist/reactist/assets/15199/1720b6e5-b295-4fff-b1b7-81c56f164000">

**Comment by MahirMahdi** [comment]
> Please, go to [this storybook story](https://doist.github.io/reactist/?path=/docs/design-system-textarea--auto-expand-story) and start typing in a text area at the top (the one that says it has auto-expand enabled). You should be able to reproduce:
> 
> <img alt="CleanShot 2023-06-05 at 08 20 31@2x" width="655" src="https://user-images.githubusercontent.com/15199/243350570-1720b6e5-b295-4fff-b1b7-81c56f164000.png">
> I have updated the issue title and description to make this more clear. It was not as clear before.

I think there's something wrong with the last build. The styles are not applied to the storybook.
![Screenshot 2023-06-07 101857](https://github.com/Doist/reactist/assets/66949598/d8b006db-60c5-495a-9966-5b1216e539ba)

**Comment by MahirMahdi** [comment]
@gnapse I believe I fixed it. `overflow-wrap` by default is `break-word` that's why it was expanding horizontally when typing text without spaces. When I changed it to `anywhere`, it stopped expanding.



![Screenshot 2023-06-17 112717](https://github.com/Doist/reactist/assets/66949598/282b5072-8b9b-482c-84f6-f224072439ce)

**Comment by gnapse** [comment]
@MahirMahdi can you open a pull request with the proposed change?

**Comment by MahirMahdi** [comment]
> @MahirMahdi can you open a pull request with the proposed change?

Yes, no problem. On it.
